//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iNKORE.UI.WPF.Modern {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iNKORE.UI.WPF.Modern.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 See more 的本地化字符串。
        /// </summary>
        internal static string AppBarMoreButtonClosedToolTip {
            get {
                return ResourceManager.GetString("AppBarMoreButtonClosedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More app bar 的本地化字符串。
        /// </summary>
        internal static string AppBarMoreButtonName {
            get {
                return ResourceManager.GetString("AppBarMoreButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 See less 的本地化字符串。
        /// </summary>
        internal static string AppBarMoreButtonOpenToolTip {
            get {
                return ResourceManager.GetString("AppBarMoreButtonOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore 的本地化字符串。
        /// </summary>
        internal static string IgnoreMenuItemLabel {
            get {
                return ResourceManager.GetString("IgnoreMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proofing 的本地化字符串。
        /// </summary>
        internal static string ProofingMenuItemLabel {
            get {
                return ResourceManager.GetString("ProofingMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold the selected text 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionBold {
            get {
                return ResourceManager.GetString("TextCommandDescriptionBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the selected content to the clipboard 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionCopy {
            get {
                return ResourceManager.GetString("TextCommandDescriptionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the selected content and put it on the clipboard 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionCut {
            get {
                return ResourceManager.GetString("TextCommandDescriptionCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italicize the selected text 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionItalic {
            get {
                return ResourceManager.GetString("TextCommandDescriptionItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert the contents of the clipboard at the current location 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionPaste {
            get {
                return ResourceManager.GetString("TextCommandDescriptionPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeat the most recently undone action 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionRedo {
            get {
                return ResourceManager.GetString("TextCommandDescriptionRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all content 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionSelectAll {
            get {
                return ResourceManager.GetString("TextCommandDescriptionSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underline the selected text 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionUnderline {
            get {
                return ResourceManager.GetString("TextCommandDescriptionUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse the most recent action 的本地化字符串。
        /// </summary>
        internal static string TextCommandDescriptionUndo {
            get {
                return ResourceManager.GetString("TextCommandDescriptionUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyBold {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyCopy {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyCut {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyItalic {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyPaste {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyRedo {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeySelectAll {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeySelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 U 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyUnderline {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z 的本地化字符串。
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyUndo {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelBold {
            get {
                return ResourceManager.GetString("TextCommandLabelBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelCopy {
            get {
                return ResourceManager.GetString("TextCommandLabelCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelCut {
            get {
                return ResourceManager.GetString("TextCommandLabelCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelItalic {
            get {
                return ResourceManager.GetString("TextCommandLabelItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelPaste {
            get {
                return ResourceManager.GetString("TextCommandLabelPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelRedo {
            get {
                return ResourceManager.GetString("TextCommandLabelRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelSelectAll {
            get {
                return ResourceManager.GetString("TextCommandLabelSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underline 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelUnderline {
            get {
                return ResourceManager.GetString("TextCommandLabelUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string TextCommandLabelUndo {
            get {
                return ResourceManager.GetString("TextCommandLabelUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
    }
}
